version: '3.8'

services:
  edrefcard:
    build: .
    volumes:
      - ./configs:/app/www/configs
    environment:
      - PYTHONUNBUFFERED=1
      - EDREFCARD_ADMIN_USER
      - EDREFCARD_ADMIN_PASS
      - FLASK_SECRET_KEY
      - APP_URL
    user: root
    restart: unless-stopped
